### ISSUE TITLE
Error running start_bolts.FCMacro in FreeCAD 0.18

### ISSUE THREAD

**Issue by weirdgyn** [boltsparts/BOLTSFC#20]
After installing the plugin I tried to run the macro. This's the result from the console:

```
Traceback (most recent call last):
  File "C:/Users/weird.TUX/AppData/Roaming/FreeCAD/Macro/start_bolts.FCMacro", line 1, in <module>
    import BOLTS
  File "C:\Users\weird.TUX\AppData\Roaming\FreeCAD\Mod\BOLTSFC\BOLTS\__init__.py", line 44, in <module>
    from .gui import freecad_bolts as boltsgui
  File "C:\Users\weird.TUX\AppData\Roaming\FreeCAD\Mod\BOLTSFC\BOLTS\gui\freecad_bolts.py", line 30, in <module>
    Ui_BoltsWidget,QBoltsWidget = uic.loadUiType(join(bolts_path,'bolts_widget.ui'))
<class 'SyntaxError'>: Missing parentheses in call to 'exec' (<string>, line 15)
```

**Comment by berndhahnebach** [comment]
you should use the latest 0.18.4 FreeCAD version. This error was fixed in 0.18 fixes ... 
https://forum.freecadweb.org/viewtopic.php?f=10&t=36186
