### ISSUE TITLE
uic import failed

### ISSUE THREAD

**Issue by LuisLlana** [boltsparts/BOLTSFC#26]
Hello,
  I have just installed the BOLTSFC macros in freecad using the macros manager. When I try to start the macro I obtain the following error:
```
uic import failed. Make sure that the pyside tools are installedTraceback (most recent call last):
  File "/home/luis/.FreeCAD/Macro/start_bolts.FCMacro", line 1, in <module>
    import BOLTS
  File "/home/luis/.FreeCAD/Mod/BOLTSFC/BOLTS/__init__.py", line 44, in <module>
    from .gui import freecad_bolts as boltsgui
  File "/home/luis/.FreeCAD/Mod/BOLTSFC/BOLTS/gui/freecad_bolts.py", line 30, in <module>
    Ui_BoltsWidget,QBoltsWidget = uic.loadUiType(join(bolts_path,'bolts_widget.ui'))
  File "<string>", line 1, in <module>pysideuic
<class 'ModuleNotFoundError'>: No module named 'pysideuic'
```

I am running freecad in Ubuntu 20.04. I have tried `pip install pysideuic` and `python2 -m pip install pysideuic` with no success.

**Comment by berndhahnebach** [comment]
Which FreeCAD version do you have installed? How did you install it?

**Comment by berndhahnebach** [comment]
Found this. I might not help, but it is a start.  https://forum.freecadweb.org/viewtopic.php?f=3&t=34818

**Comment by berndhahnebach** [comment]
Does this gives any error from a FreeCAD Python console?

`from FreeCADGui import PySideUic as uic`

**Comment by berndhahnebach** [comment]
Furthermore you could dry ... 

`wid = uic.loadUiType(join(App.getHomePath(), "Mod", "Fem", "Resources", "ui", "ConstraintSectionPrint.ui"))`

this should result in:

`
>>> 
>>> wid = uic.loadUiType(join(App.getHomePath(), "Mod", "Fem", "Resources", "ui", "ConstraintSectionPrint.ui"))
>>> wid
(<class 'Ui_Form'>, <class 'PySide2.QtWidgets.QWidget'>)
>>> 
`

**Comment by LuisLlana** [comment]
Hello,
  I was using freecad from the ubuntu repositories (version 0.18). I have installed the ppa version, it installs version 0.19. I obtain the same error.
  The first command does not give any errors. The second does not work. First, I haved the join syntax (it said than function was undefined):

`>>> wid = uic.loadUiType("/".join([App.getHomePath(), "Mod", "Fem", "Resources", "ui", "ConstraintSectionPrint.ui"]))`

It gives a similar error:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pyside2uic'
```

**Comment by berndhahnebach** [comment]
Mhh I am on Debian Buster ... I am able to explicit install this with:

`sudo apt-get install python3-pyside2uic`

But it seams only available on Buster ...

https://packages.debian.org/search?keywords=python3-pyside2uic&searchon=names&suite=buster&section=all

**Comment by berndhahnebach** [comment]
Which Python does your FreeCAD run with? Hopefully Python 3 ...

**Comment by berndhahnebach** [comment]
BTW:
BOLTS does run for me on a Virtual Machines which only has the packages installed needed to compile FreeCAD.

strange ... see https://wiki.freecadweb.org/Compile_on_Linux#Python_3_and_Qt5 there it says one should install `python3-pyside2uic` on ubuntu to compile FreeCAD ...

**Comment by LuisLlana** [comment]
I use python3 indeed. It seems that this package does not exist in ubuntu. 
```
sudo apt-get install python3-pyside2uic
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate packagubuntu 20.04 pyside2uice python3-pyside2uic

```

**Comment by berndhahnebach** [comment]
https://forum.freecadweb.org/viewtopic.php?f=42&t=37458&start=160#p396635

and 

https://bugs.launchpad.net/ubuntu/+source/pyside-tools/+bug/1873613

might help ...

**Comment by berndhahnebach** [comment]
related: https://github.com/boltsparts/BOLTS/issues/211
