### ISSUE TITLE
Error module pyside2uic missing

### ISSUE THREAD

**Issue by szzer** [boltsparts/BOLTSFC#33]
I tried to use the BOLTSFC workbench in the new freecad 0.19 installer version.

I encounter the following issue:

![image](https://user-images.githubusercontent.com/71587569/111207432-e8778600-85c9-11eb-9158-69576d4f6563.png)

I see that this has been an issue in the past, but that was on unbuntu. But i'm using Windows.

OS: Windows 10 Version 2004
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.24275 (Git)
Build type: Release
Branch: releases/FreeCAD-0-19
Hash: f4574cf02d08fedd0a416d798b7dfef0ca2b5579
Python version: 3.8.6+
Qt version: 5.15.1
Coin version: 4.0.1
OCC version: 7.5.0
Locale: Dutch/Netherlands (nl_NL)

Is there an existing solution to solve this issue?

**Comment by IGB-Germany** [comment]
Me too:

OS: Windows 10 Version 1909
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.24276 (Git)
Build type: Release
Branch: releases/FreeCAD-0-19
Hash: a88db11e0a908f6e38f92bfc5187b13ebe470438
Python version: 3.8.6+
Qt version: 5.15.1
Coin version: 4.0.1
OCC version: 7.5.0
Locale: German/Germany (de_DE)


16:18:34  uic import failed. Make sure that the pyside tools are installedTraceback (most recent call last):
  File "C:/Users/Marcus/AppData/Roaming/FreeCAD/Macro/start_bolts.FCMacro", line 1, in <module>
    import BOLTS
  File "C:\Program Files\FreeCAD\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\Marcus\AppData\Roaming\FreeCAD\Mod\BOLTSFC\BOLTS\__init__.py", line 44, in <module>
    from .gui import freecad_bolts as boltsgui
  File "C:\Program Files\FreeCAD\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\Marcus\AppData\Roaming\FreeCAD\Mod\BOLTSFC\BOLTS\gui\freecad_bolts.py", line 37, in <module>
    Ui_BoltsWidget, QBoltsWidget = uic.loadUiType(
  File "<string>", line 1, in <module>
  File "C:\Program Files\FreeCAD\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
<class 'ModuleNotFoundError'>: No module named 'pyside2uic'
16:21:38  uic import failed. Make sure that the pyside tools are installedTraceback (most recent call last):
  File "C:/Users/Marcus/AppData/Roaming/FreeCAD/Macro/start_bolts.FCMacro", line 1, in <module>
    import BOLTS
  File "C:\Program Files\FreeCAD\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\Marcus\AppData\Roaming\FreeCAD\Mod\BOLTSFC\BOLTS\__init__.py", line 44, in <module>
    from .gui import freecad_bolts as boltsgui
  File "C:\Program Files\FreeCAD\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\Marcus\AppData\Roaming\FreeCAD\Mod\BOLTSFC\BOLTS\gui\freecad_bolts.py", line 37, in <module>
    Ui_BoltsWidget, QBoltsWidget = uic.loadUiType(
  File "<string>", line 1, in <module>
  File "C:\Program Files\FreeCAD\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
<class 'ModuleNotFoundError'>: No module named 'pyside2uic'

**Comment by wytr** [comment]
Same Issue over here. Is anyone still working on this repository?

**Comment by dkurok** [comment]
Same issue here on a Windows 2019 server machine:

`11:39:55  uic import failed. Make sure that the pyside tools are installedTraceback (most recent call last):
  File "C:/Users/XXX/AppData/Roaming/FreeCAD/Macro/start_bolts.FCMacro", line 1, in <module>
    import BOLTS
  File "C:\Program Files\FreeCAD 0.19\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\XXX\AppData\Roaming\FreeCAD\Mod\BOLTSFC\BOLTS\__init__.py", line 44, in <module>
    from .gui import freecad_bolts as boltsgui
  File "C:\Program Files\FreeCAD 0.19\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\XXX\AppData\Roaming\FreeCAD\Mod\BOLTSFC\BOLTS\gui\freecad_bolts.py", line 38, in <module>
    Ui_BoltsWidget, QBoltsWidget = uic.loadUiType(
  File "<string>", line 1, in <module>
  File "C:\Program Files\FreeCAD 0.19\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
<class 'ModuleNotFoundError'>: No module named 'pyside2uic'`

Python-Konsole in FreeCad 0.19:
>>> import sys
>>> sys.version
'3.8.6+ (heads/3.8-dirty:a12f459ec2, Nov  5 2020, 12:01:10) [MSC v.1927 64 bit (AMD64)]'

**Comment by berndhahnebach** [comment]
https://github.com/boltsparts/BOLTSFC/issues/40
