### ISSUE TITLE
No module named 'pyside2uic'

### ISSUE THREAD

**Issue by jx2014** [boltsparts/BOLTSFC#34]
Hi,

I have installed BOLTS to FreeCad 0.19 on windows 10. 
After restarting FreeCad, I manually ran import BOLTS under Python console and encountered the following error:

```
>>> import BOLTS
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\FreeCAD 0.19\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\jx2014\AppData\Roaming\FreeCAD\Mod\BOLTSFC\BOLTS\__init__.py", line 44, in <module>
    from .gui import freecad_bolts as boltsgui
  File "C:\Program Files\FreeCAD 0.19\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\jx2014\AppData\Roaming\FreeCAD\Mod\BOLTSFC\BOLTS\gui\freecad_bolts.py", line 38, in <module>
    Ui_BoltsWidget, QBoltsWidget = uic.loadUiType(
  File "<string>", line 1, in <module>
  File "C:\Program Files\FreeCAD 0.19\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'pyside2uic'
```

Do i need to install pyside2uic manually some how?

**Comment by jx2014** [comment]
'''
>>> import sys
>>> sys.version
'3.8.6+ (heads/3.8-dirty:a12f459ec2, Nov  5 2020, 12:01:10) [MSC v.1927 64 bit (AMD64)]'
'''

**Comment by dkurok** [comment]
Same issue here on a Windows 2019 server machine:

`11:39:55  uic import failed. Make sure that the pyside tools are installedTraceback (most recent call last):
  File "C:/Users/XXX/AppData/Roaming/FreeCAD/Macro/start_bolts.FCMacro", line 1, in <module>
    import BOLTS
  File "C:\Program Files\FreeCAD 0.19\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\XXX\AppData\Roaming\FreeCAD\Mod\BOLTSFC\BOLTS\__init__.py", line 44, in <module>
    from .gui import freecad_bolts as boltsgui
  File "C:\Program Files\FreeCAD 0.19\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\XXX\AppData\Roaming\FreeCAD\Mod\BOLTSFC\BOLTS\gui\freecad_bolts.py", line 38, in <module>
    Ui_BoltsWidget, QBoltsWidget = uic.loadUiType(
  File "<string>", line 1, in <module>
  File "C:\Program Files\FreeCAD 0.19\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
<class 'ModuleNotFoundError'>: No module named 'pyside2uic'`

Python-Konsole in FreeCad 0.19:
>>> import sys
>>> sys.version
'3.8.6+ (heads/3.8-dirty:a12f459ec2, Nov  5 2020, 12:01:10) [MSC v.1927 64 bit (AMD64)]'

**Comment by berndhahnebach** [comment]
https://github.com/boltsparts/BOLTSFC/issues/40
