### ISSUE TITLE
No module named 'pyside2uic' on Windows and Linux

### ISSUE THREAD

**Issue by berndhahnebach** [boltsparts/BOLTSFC#40]
this has been an issue for a long time. The import for the method loadUiType was missing, but in FreeCAD the method loadUi is for sure available because internal modules dependend on it. Thus it was switched from loadUiType to loadUi. Thus all the import problems in this regard should be gone ... 

https://github.com/boltsparts/BOLTSFC/issues/36
https://forum.freecadweb.org/viewtopic.php?f=4&t=59849

https://github.com/boltsparts/BOLTS/commit/72676c7d413e444fb01bf8279a2b3337c560f894
https://github.com/boltsparts/BOLTS/commit/cb2f514e858f13a95300083b05fcbf0b904d55a6

**Comment by IGB-Germany** [comment]
Add-On Manager installs now as intended.
But Makro doesnt work.
Here the information:

OS: Windows 10 Version 2009
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.24276 (Git)
Build type: Release
Branch: releases/FreeCAD-0-19
Hash: a88db11e0a908f6e38f92bfc5187b13ebe470438
Python version: 3.8.6+
Qt version: 5.15.1
Coin version: 4.0.1
OCC version: 7.5.0
Locale: German/Germany (de_DE)

07:22:12 uic import failed. Make sure that the pyside tools are installedTraceback (most recent call last):
File "C:/Users/Marcus/AppData/Roaming/FreeCAD/Macro/start_bolts.FCMacro", line 1, in
import BOLTS
File "C:\Program Files\FreeCAD\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport_feature_.py", line 142, in import
return original_import(name, *args, **kwargs)
File "C:\Users\Marcus\AppData\Roaming\FreeCAD\Mod\BOLTSFC\BOLTS_init.py", line 44, in
from .gui import freecad_bolts as boltsgui
File "C:\Program Files\FreeCAD\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport_feature_.py", line 142, in import
return original_import(name, *args, **kwargs)
File "C:\Users\Marcus\AppData\Roaming\FreeCAD\Mod\BOLTSFC\BOLTS\gui\freecad_bolts.py", line 37, in
Ui_BoltsWidget, QBoltsWidget = uic.loadUiType(
File "", line 1, in
File "C:\Program Files\FreeCAD\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport_feature.py", line 142, in _import
return original_import(name, *args, **kwargs)
<class 'ModuleNotFoundError'>: No module named 'pyside2uic'

**Comment by berndhahnebach** [comment]
More fixes have been pushed. Would you try again to update BOLTS with the AddOn manager in FreeCAD!
